.hparEnv <- new.env(parent=emptyenv(), hash=TRUE)

## these rda files have been generated by inst/scripts/biomaRt.R
load(dir(system.file(package = "hpar", dir = "extdata"),
         full.name = TRUE,
         pattern = "hpaRelease.rda"))

assign("hpaVersion", hpaRelease$version, envir = .hpaEnv)
assign("hpaDate", hpaRelease$date, envir = .hpaEnv)


