.hparEnv <- new.env(parent=emptyenv(), hash=TRUE)

## these rda files have been generated by inst/scripts/biomaRt.R
load(dir(system.file(package = "hpar", dir = "extdata"),
         full.name = TRUE,
         pattern = "hpaRelease.rda"))

assign("hpaVersion", hpaRelease$version, envir = .hparEnv)
assign("hpaDate", hpaRelease$date, envir = .hparEnv)
assign("hpaEnsembl", hpaRelease$ensembl, envir = .hparEnv)

##' Function used to set the \code{what} \code{hpar} option. 
##'
##' @title Sets the 'hpar' options
##' @param what A \code{character} defining the default data
##' to be queries. Choices are "NormalTissue", "Rna" or
##' "SubcellularLoc", or any unambiguous prefix.
##' @return Returns the set value of the \code{hpar} option.
##' Used for its side effect.
##' @author Laurent Gatto
##' @examples
##' oldOpt <- getHparOptions()
##' oldOpt$what
##' setHparOptions("Rna")
##' getHparOptions()
##' setHparOptions(oldOpt$what)
setHparOptions <- function(what = c("NormalTissue", "Rna", "SubcellularLoc")) {
  what <- match.arg(what)
  opts <- getOption("hpar")
  if (is.null(opts))
    opts <- list()
  opts$what <- what
  options("hpar" = opts)
  invisible(what)
}

##' Returns the \code{hapr} options. Currently, there is only
##' one, \code{what}. See \code{\link{setHparOptions}} for
##' details and examples.
##'
##' @title Returns the \code{hpar} option.
##' @return A \code{list} with the \code{hpar} option(s). 
##' @author Laurent Gatto
getHparOptions <- function() {
  options("hpar")  
}
  
